module.exports = {
  // graphics
  NUM_TILES: 384,
  ROWS_IN_TILE: 8,
  COLS_IN_TILE: 8,
  SCREEN_WIDTH: 160,
  SCREEN_HEIGHT: 144,
  NUM_SPRITES: 40,
  CANVAS_ELEMENTS_PER_PIXEL: 4,
  TILES_IN_SCREEN_WIDTH: 32,
};
